function rotAngle = rotatePosition(obj, trialIndex)
% rotatePosition - Align position data with the camera window, based on the
% recorded box corners (removes misalignment of box walls and camera axes)
% package: scanpix.maps
%
% Positions are rotated about the box centre so that the NW-NE box edge is
% parallel to the x-axis. Works on the final, processed positions, i.e. after
% they might have been scaled to a common ppm and/or fit to the environment.
% To keep everything in the same frame we also rotate:
%   - head direction data
%   - box corners (trialMetaData.envBorderCoords) - this also means that
%     running the function again on the same trial will leave data unchanged
%   - object positions (trialMetaData.objectPos) and, for behaviour data,
%     feederCoords and rewardZoneCentre - these stay in raw camera pixels, so
%     downstream scaling/offsetting (e.g. getBarrCoords, pp_analyse) still works
% Circular environments or trials without box corners are left untouched.
%
% Syntax:
%       scanpix.maps.rotatePosition(obj, trialIndex)
%       rotAngle = scanpix.maps.rotatePosition(obj, trialIndex)
%
% Inputs:
%    obj         - dacq or npix class object
%    trialIndex  - numeric index of trial(s) to be rotated
%
% Outputs:
%    rotAngle    - angle (deg) positions were rotated by (NaN = not rotated)
%
% see also: scanpix.maps.scalePosition; scanpix.helpers.findBoxCorners
%
% LM 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
arguments
    obj {mustBeA(obj,'scanpix.ephys')}
    trialIndex (1,:) {mustBeNumeric}
end

%%
rotAngle = nan(1,length(trialIndex));

for i = 1:length(trialIndex)
    trInd = trialIndex(i);

    % we need the full set of corners (NW,NE,SE,SW) as generated by scanpix.helpers.findBoxCorners
    corners = obj.trialMetaData(trInd).envBorderCoords;
    if size(corners,2) ~= 4 || ~isempty(regexp(obj.trialMetaData(trInd).trialType,'circle','once'))
        warning('scaNpix::maps::rotatePosition:No box corners for trial %i (or circular environment). Positions not rotated.',trInd);
        continue
    end

    % add scaling factor in case data is scaled to common ppm
    if obj.trialMetaData(trInd).PosIsScaled
        scaleFact = obj.trialMetaData(trInd).ppm / obj.trialMetaData(trInd).ppm_org;
    else
        scaleFact = 1;
    end
    % NOTE: envBorderCoords are already scaled to common ppm when loading pos data, so only the raw
    % object coordinates need scaling. Box centre in raw camera pixels:
    boxCentreRaw = mean(corners,2)' ./ scaleFact;

    % in case pos is fitted to visited environment or embedded in camera window need to adjust coordinates further
    corners = corners';
    if obj.trialMetaData(trInd).PosIsFitToEnv{1}
        corners = corners - obj.trialMetaData(trInd).PosIsFitToEnv{2}(:)';
    end
    boxCentre = mean(corners,1);

    % angle of misalignment (NW->NE edge) - rotation is the same in all frames, as scaling and offset don't change angles
    refPoints = corners(1:2,:)';
    theta     = atan2(diff(refPoints(2,:)),diff(refPoints(1,:)));

    % rotate positions about box centre
    obj.posData(1).XY{trInd} = rotatePoints(obj.posData(1).XY{trInd} - boxCentre, refPoints) + boxCentre;

    % head direction - rotatePoints maps angle phi to phi-theta
    if ~isempty(obj.posData(1).direction) && length(obj.posData(1).direction) >= trInd && ~isempty(obj.posData(1).direction{trInd})
        obj.posData(1).direction{trInd} = mod(obj.posData(1).direction{trInd} - theta*180/pi, 360);
    end

    % box corners (stored in scaled, but not fit-to-env frame)
    cornersStored = obj.trialMetaData(trInd).envBorderCoords';
    centreStored  = mean(cornersStored,1);
    obj.trialMetaData(trInd).envBorderCoords = (rotatePoints(cornersStored - centreStored, refPoints) + centreStored)';

    % if data were fit to env (scanpix.maps.scalePosition) before rotation, the aligned box is now inset within the
    % fitted frame (and sticks out on the far side) - shift data back by that inset and update the offset accordingly
    if obj.trialMetaData(trInd).PosIsFitToEnv{1}
        cornersRot = rotatePoints(corners - boxCentre, refPoints) + boxCentre;
        inset      = min(cornersRot,[],1) - min(corners,[],1);
        obj.posData(1).XY{trInd}                   = obj.posData(1).XY{trInd} - inset;
        obj.trialMetaData(trInd).PosIsFitToEnv{2} = reshape(obj.trialMetaData(trInd).PosIsFitToEnv{2},1,[]) + inset;
        if numel(obj.trialMetaData(trInd).PosIsFitToEnv) >= 3 && isstruct(obj.trialMetaData(trInd).PosIsFitToEnv{3})
            obj.trialMetaData(trInd).PosIsFitToEnv{3}.shift = obj.trialMetaData(trInd).PosIsFitToEnv{3}.shift - inset;
        end
    end

    % object/feeder/reward zone positions (stored in raw camera pixels as X1Y1,X2Y2,... - a trailing odd element, e.g.
    % barrier radius, is left as is)
    rawCoordFields = {'objectPos','feederCoords','rewardZoneCentre'};
    for f = rawCoordFields
        if isfield(obj.trialMetaData(trInd),f{1}) && isnumeric(obj.trialMetaData(trInd).(f{1})) && numel(obj.trialMetaData(trInd).(f{1})) >= 2
            obj.trialMetaData(trInd).(f{1}) = rotateRawCoords(obj.trialMetaData(trInd).(f{1}), boxCentreRaw, refPoints);
        end
    end

    % sanity check - binning in rate maps assumes positive coordinates for data fit to env
    if obj.trialMetaData(trInd).PosIsFitToEnv{1} && any(obj.posData(1).XY{trInd}(:) <= 0)
        warning('scaNpix::maps::rotatePosition:%i position samples <= 0 after rotation in trial %i. These will cause trouble when binning rate maps.',sum(any(obj.posData(1).XY{trInd} <= 0,2)),trInd);
    end

    rotAngle(i) = theta*180/pi;
end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function coords = rotateRawCoords(coords, centre, refPoints)
% rotate flat X1Y1,X2Y2,... list about centre
nPairs = floor(numel(coords)/2);
xy     = [reshape(coords(1:2:2*nPairs),[],1), reshape(coords(2:2:2*nPairs),[],1)];
xy     = rotatePoints(xy - centre, refPoints) + centre;
coords(1:2*nPairs) = reshape(xy',1,[]);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function xyRot = rotatePoints(xy,refPoints)
% rotate points (nx2) by minus the angle of the line through refPoints
% ([x1 x2; y1 y2]), i.e. that line ends up parallel to the x-axis
theta = atan2(diff(refPoints(2,:)),diff(refPoints(1,:)));
R     = [cos(theta) -sin(theta); sin(theta) cos(theta)]; % rotation matrix
xyRot = xy * R;
end
